# Generated by Django 2.2.13 on 2022-04-20 15:43

import ajaximage.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='image'),
        ),
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='image')),
                ('title', models.CharField(blank=True, max_length=250, verbose_name='title')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recipe', verbose_name='recipe')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
    ]
