# Generated by Django 2.2.13 on 2022-04-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredientnutritionalvalue_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientnutritionalvalue',
            name='slug',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
