# Generated by Django 2.2.13 on 2022-04-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_recipe_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
