# Generated by Django 2.2.13 on 2022-04-24 19:49

import ajaximage.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220425_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=ajaximage.fields.AjaxImageField(blank=True, null=True, verbose_name='image'),
        ),
    ]
